[package]
name = "spotify-dbus"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dbus = "0.9.7"
mpris = "2.0.0"
termion = "2.0.1"
